### ISSUE TITLE
Decide how to organize the pattern catalog

### ISSUE THREAD

**Issue by skreutzer** [holtzermann17/PeeragogyPatterns#3]
This repository likely is a little bit outdated. The question is why the patterns shouldn't be maintained at one single place, to end up in the handbook and as a separate catalog (websites, apps, printed catalog without other handbook contents, databases/glossaries as a source for augmentation, cards, etc.) from the same source.

**Comment by holtzermann17** [comment]
Yeah, I think we used this repo for the paper in 2015.  It's not maintained as such. I will "Archive" it so that's clear. The current authoritative source of the patterns should be in the peeragogy.github.io repo.  Definitely we should add more ways to process the patterns!
